name: Build category fallbacks JSON

on:
  push:
    paths:
      - "categorized/**"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build-fallbacks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Prepare arrays from text files
        run: |
          set -euo pipefail

          # Helper to turn a txt file (one prompt per line) into JSON array
          to_json_array () {
            local file="$1"
            if [ -f "$file" ]; then
              # Read lines, drop empties, output JSON array
              jq -Rs '
                split("\n")
                | map(. | gsub("\\r$"; ""))      # strip CR if present
                | map(select(length > 0))         # remove empty lines
              ' < "$file"
            else
              echo "[]"  # missing file -> empty array
            fi
          }

          NB_JSON=$(to_json_array "categorized/new-believers.txt")
          DS_JSON=$(to_json_array "categorized/deep-study.txt")
          AP_JSON=$(to_json_array "categorized/application-prompts.txt")

          # General fallback (static, safe defaults)
          GENERAL_JSON='[
            "What does John 1:1 mean?",
            "Help me understand Romans 8:28.",
            "Show me Psalm 23 in the KJV.",
            "Give me a short devotional."
          ]'

          jq -n \
            --argjson general "$GENERAL_JSON" \
            --argjson nb "$NB_JSON" \
            --argjson ds "$DS_JSON" \
            --argjson ap "$AP_JSON" \
            '{ general: $general, newBelievers: $nb, deepStudy: $ds, application: $ap }' \
            > categorized/fallbacks.json

      - name: Commit changes (if any)
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add categorized/fallbacks.json
            git commit -m "build: update categorized/fallbacks.json from txt sources"
            git push
            echo "fallbacks.json updated."
          else
            echo "No changes to commit."
          fi
